/**
 * Session.js — Mongoose model for storing repository analysis sessions.
 *
 * Each session corresponds to one analyzed GitHub repository and stores:
 * - Repository metadata and analysis results
 * - Chat history for conversational queries
 * - Vectorization status for the RAG pipeline
 */

import mongoose from 'mongoose';

const { Schema, model } = mongoose;

// ─── Chat Message Sub-Schema ─────────────────────────────────────────────────
// Represents a single message in the conversation history
const ChatMessageSchema = new Schema(
  {
    role: {
      type: String,
      enum: ['user', 'assistant', 'system'],
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
    timestamp: {
      type: Date,
      default: Date.now,
    },
  },
  { _id: false } // No separate _id for sub-documents — keeps the array lean
);

// ─── Session Schema ──────────────────────────────────────────────────────────
const SessionSchema = new Schema(
  {
    // Unique session identifier (generated by the client or server, e.g., UUID)
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // The full GitHub URL that was analyzed
    repoUrl: {
      type: String,
      required: true,
      trim: true,
    },

    // Parsed components of the URL for quick access
    owner: {
      type: String,
      trim: true,
    },
    repo: {
      type: String,
      trim: true,
    },

    // Raw metadata returned by the GitHub API (stars, forks, language, etc.)
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },

    // Detected tech stack from languages + dependency files
    techStack: {
      type: [String],
      default: [],
    },

    // Language byte-count map: { "JavaScript": 45000, "CSS": 8000 }
    languages: {
      type: Schema.Types.Mixed,
      default: {},
    },

    // Whether the repository has been chunked and embedded into the vector store
    vectorized: {
      type: Boolean,
      default: false,
    },

    // Number of chunks stored in the vector store after embedding
    totalChunks: {
      type: Number,
      default: 0,
    },

    // Number of files processed during vectorization
    filesProcessed: {
      type: Number,
      default: 0,
    },

    // Conversation history for this session's chat feature
    chatHistory: {
      type: [ChatMessageSchema],
      default: [],
    },
  },
  {
    // Automatically manage createdAt and updatedAt timestamps
    timestamps: true,

    // Remove version key (__v) from documents
    versionKey: false,
  }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────
// Compound index for quickly finding sessions by owner + repo
SessionSchema.index({ owner: 1, repo: 1 });

// TTL index: automatically delete sessions older than 7 days (604800 seconds)
// This prevents unbounded growth in the database
SessionSchema.index({ createdAt: 1 }, { expireAfterSeconds: 604800 });

// ─── Instance Methods ─────────────────────────────────────────────────────────
/**
 * Appends a message to the chat history and saves the document.
 * @param {string} role    - 'user' | 'assistant' | 'system'
 * @param {string} content - Message text
 */
SessionSchema.methods.addMessage = async function (role, content) {
  this.chatHistory.push({ role, content, timestamp: new Date() });
  // Keep only the last 100 messages to prevent unbounded growth
  if (this.chatHistory.length > 100) {
    this.chatHistory = this.chatHistory.slice(-100);
  }
  await this.save();
};

// ─── Static Methods ───────────────────────────────────────────────────────────
/**
 * Finds an existing session or creates a new one.
 * @param {string} sessionId
 * @param {Object} defaults  - Fields to set when creating a new document
 */
SessionSchema.statics.findOrCreate = async function (sessionId, defaults = {}) {
  let session = await this.findOne({ sessionId });
  if (!session) {
    session = await this.create({ sessionId, ...defaults });
  }
  return session;
};

// ─── Model Export ─────────────────────────────────────────────────────────────
const Session = model('Session', SessionSchema);
export default Session;
